### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by SamMousa** [mrohnstock/datatables-plugins#2]
Would it not make sense to add plugin dependencies here as well?

For example datetime-moment requires the "moment" bower package.

**Comment by drmonty** [comment]
If you prefer to use any kind of plugin available here, yes, but I don't think that anyone will use more than one or two plugins available here (actually I only use one).

I think, if you want to use one of the plugins listed in this repo, you would already using the dependency, wouldn't you?
