### ISSUE TITLE
main.js file

### ISSUE THREAD

**Issue by coremi** [mrohnstock/datatables-plugins#3]
Your bower.json points to a "main.js" file, that does not exist. I know that it might not make much sense to actually have that file (assuming it's a file that simply contains all plugins), but it seams to be the more common practice.

I am currently trying to use a generator for a requirejs config-file (https://github.com/yeoman/bower-requirejs) that seams to read the main-property of each required bower-package and am getting errors because of the non-existant file.

**Comment by mrohnstock** [comment]
4af7a7f Sorry for the delay, I've created an empty main.js, so this should fit your need, shouldn't it?
