### ISSUE TITLE
Comments in lang files

### ISSUE THREAD

**Issue by xvonabur** [mrohnstock/datatables-plugins#4]
Hello! According to  https://github.com/DataTables/Plugins/issues/131 and https://github.com/DataTables/Plugins/issues/18, we can't use lang files out the box, because of the comments. It's not convenient to install bower package, copy a file and remove comments in order to use it with datatables. Maybe it's time to remove comments from lang files? 

P.S. By the way, [CDN .json lang](http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/German.json) files doesn't have them and they perfectly work.
P.P.S. I can send a pull request with comments removed.

**Comment by nelson6e65** [comment]
:+1: yes. I had to remove comments manually too, and then works fine.

**Comment by mrohnstock** [comment]
c23e47fcca3d3474e7b14d55f74cb028d15a6664 I've created a small bashscript, which will create these required json-language files out of the lang-files for every new release.
